# run on container-based build:
sudo: false
language: perl
matrix:
  include:
    - perl: '5.24'
      addons:
        postgresql: "9.3"
      env:
        - DB_TESTING=1
    - perl: '5.22'
      addons:
        postgresql: "9.3"
      env:
        - DB_TESTING=1
    - perl: '5.20'
      addons:
        postgresql: "9.4"
      env:
        - COVERAGE=1
    - perl: '5.18'
      addons:
        postgresql: "9.4"
      env:
        - COA_TESTING=1
    - perl: '5.16'
      addons:
        postgresql: "9.3"
      env:
        - DB_TESTING=1
    - perl: '5.14'
      addons:
        postgresql: "9.2"
      env:
        - DB_TESTING=1
    - perl: '5.12'
      addons:
        postgresql: "9.1"
      env:
        - DB_TESTING=1
    - perl: '5.10'
      addons:
        postgresql: "9.3"
      env:
        - DB_TESTING=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V

install:
  - cpanm --notest --quiet --with-develop --installdeps .
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cp ledgersmb.conf.default ledgersmb.conf

before_script:
  - coverage-setup

script:
   export RELEASE_TESTING=1 && PGUSER=postgres PGPASSWORD=test LSMB_TEST_DB=1 LSMB_NEW_DB=lsmb13installtest prove

after_success:
  - coverage-report
