//>>built
define("lsmb/iframe","module require dojo/request/watch dojo/request/util dojo/request/handlers dojo/_base/lang dojo/io-query dojo/query dojo/has dojo/dom dojo/dom-construct dojo/cookie dojo/_base/window dojo/NodeList-dom".split(" "),function(C,D,E,r,F,z,A,G,s,B,t,w,d){function H(a){return!this.isFulfilled()}function I(a){return!!this._finished||"requested"!==w(u)}function J(a,c){var f=a.options,d=B.byId(f.form)||this._tmpForm;if(d){for(var e=this._contentToClean,n=0;n<e.length;n++)for(var p=e[n],
k=0;k<d.childNodes.length;k++){var h=d.childNodes[k];if(h.name===p){t.destroy(h);break}}this._originalAction&&d.setAttribute("action",this._originalAction);this._originalMethod&&(d.setAttribute("method",this._originalMethod),d.method=this._originalMethod);this._originalTarget&&(d.setAttribute("target",this._originalTarget),d.target=this._originalTarget)}this._tmpForm&&(t.destroy(this._tmpForm),delete this._tmpForm);if(!c&&"requested"===w(u))try{var g=b.doc(b._frame),m=f.handleAs;if("html"!==m){if("xml"===
m)if("html"===g.documentElement.tagName.toLowerCase()){G("a",g.documentElement).orphan();var q=g.documentElement.innerText||g.documentElement.textContent,q=q.replace(/>\s+</g,"\x3e\x3c");a.text=z.trim(q)}else a.data=g;else a.text=g.getElementsByTagName("textarea")[0].value;F(a)}else a.data=g}catch(l){c=l}c?this.reject(c):this._finished||"requested"!==w(u)?this.resolve(a):this.reject(Error("Invalid dojo/request/iframe request state"))}function K(a){this._callNext()}function b(a,c,f){var d=r.parseArgs(a,
r.deepCreate(L,c),!0);a=d.url;c=d.options;if("GET"!==c.method&&"POST"!==c.method)throw Error(c.method+" not supported by dojo/request/iframe");b._frame||(b._frame=b.create(b._iframeName,v+"();"));a=r.deferred(d,null,H,I,J,K);a._callNext=function(){this._calledNext||(this._calledNext=!0,b._currentDfd=null,b._fireNextRequest())};a._legacy=f;b._dfdQueue.push(a);b._fireNextRequest();E(a);return f?a:a.promise}var x=C.id.replace(/[\/\.\-]/g,"_"),v=x+"_onload",u="request-download."+(new Date).getTime();
d.global[v]||(d.global[v]=function(){var a=b._currentDfd;a?a._finished=!0:b._fireNextRequest()});var L={method:"POST"};b.create=function(a,c,b){if(d.global[a])return d.global[a];if(d.global.frames[a])return d.global.frames[a];b||(s("config-useXDomain")&&s("config-dojoBlankHtmlUrl"),b=s("config-dojoBlankHtmlUrl")||D.toUrl("dojo/resources/blank.html"));c=t.place('\x3ciframe id\x3d"'+a+'" name\x3d"'+a+'" src\x3d"'+b+'" onload\x3d"'+c+'" style\x3d"position: absolute; left: 1px; top: 1px; height: 1px; width: 1px; visibility: hidden"\x3e',
d.body());return d.global[a]=c};b.doc=function(a){if(a.contentDocument)return a.contentDocument;var c=a.name;if(c){var b=d.doc.getElementsByTagName("iframe");if(a.document&&b[c].contentWindow&&b[c].contentWindow.document)return b[c].contentWindow.document;if(d.doc.frames[c]&&d.doc.frames[c].document)return d.doc.frames[c].document}return null};b.setSrc=function(a,b,f){a=d.global.frames[a.name];a.contentWindow&&(a=a.contentWindow);try{f?a.location.replace(b):a.location=b}catch(r){}};b._iframeName=
x+"_IoIframe";b._notifyStart=function(){};b._dfdQueue=[];b._currentDfd=null;b._fireNextRequest=function(){var a;try{if(!b._currentDfd&&b._dfdQueue.length){do a=b._currentDfd=b._dfdQueue.shift();while(a&&(a.canceled||a.isCanceled&&a.isCanceled())&&b._dfdQueue.length);if(!a||a.canceled||a.isCanceled&&a.isCanceled())b._currentDfd=null;else{var c=a.response,f=c.options,s=a._contentToClean=[],e=B.byId(f.form),n=r.notify,p=f.data||null,k;p["request.download-cookie"]=u;w(u,"requested");!a._legacy&&"POST"===
f.method&&!e?e=a._tmpForm=t.create("form",{name:x+"_form",style:{position:"absolute",top:"-1000px",left:"-1000px"}},d.body()):"GET"===f.method&&(e&&-1<c.url.indexOf("?"))&&(k=c.url.slice(c.url.indexOf("?")+1),p=z.mixin(A.queryToObject(k),p));if(e){if(!a._legacy){var h=e;do h=h.parentNode;while(h&&h!==d.doc.documentElement);h||(e.style.position="absolute",e.style.left="-1000px",e.style.top="-1000px",d.body().appendChild(e));e.name||(e.name=x+"_form")}if(p){var h=function(a,b){t.create("input",{type:"hidden",
name:a,value:b},e);s.push(a)},g;for(g in p){var m=p[g];if(z.isArray(m)&&1<m.length)for(k=0;k<m.length;k++)h(g,m[k]);else e[g]?e[g].value=m:h(g,m)}}var q=e.getAttributeNode("action"),l=e.getAttributeNode("method"),y=e.getAttributeNode("target");c.url&&(a._originalAction=q?q.value:null,q?q.value=c.url:e.setAttribute("action",c.url));if(a._legacy){if(!l||!l.value)l?l.value=f.method:e.setAttribute("method",f.method)}else a._originalMethod=l?l.value:null,l?l.value=f.method:e.setAttribute("method",f.method);
a._originalTarget=y?y.value:null;y?y.value=b._iframeName:e.setAttribute("target",b._iframeName);e.target=b._iframeName;n&&n.emit("send",c,a.promise.cancel);b._notifyStart(c);e.submit()}else f="",c.options.data&&(f=c.options.data,"string"!==typeof f&&(f=A.objectToQuery(f))),h=c.url+(-1<c.url.indexOf("?")?"\x26":"?")+f,n&&n.emit("send",c,a.promise.cancel),b._notifyStart(c),b.setSrc(b._frame,h,!0)}}}catch(v){a.reject(v)}};r.addCommonMethods(b,["GET","POST"]);return b});
//# sourceMappingURL=iframe.js.map