//>>built
define("lsmb/iframe","module require dojo/request/watch dojo/request/util dojo/request/handlers dojo/_base/lang dojo/io-query dojo/query dojo/has dojo/dom dojo/dom-construct dojo/cookie dojo/_base/window dojo/NodeList-manipulate dojo/NodeList-dom".split(" "),function(E,F,G,q,H,A,B,C,t,D,u,x,d){function I(a){return!this.isFulfilled()}function J(a){return!!this._finished||"requested"!==x(v)}function K(a,c){var f=a.options,d=D.byId(f.form)||this._tmpForm;if(d){for(var e=this._contentToClean,m=0;m<e.length;m++)for(var n=
e[m],k=0;k<d.childNodes.length;k++){var g=d.childNodes[k];if(g.name===n){u.destroy(g);break}}this._originalAction&&d.setAttribute("action",this._originalAction);this._originalMethod&&(d.setAttribute("method",this._originalMethod),d.method=this._originalMethod);this._originalTarget&&(d.setAttribute("target",this._originalTarget),d.target=this._originalTarget)}this._tmpForm&&(u.destroy(this._tmpForm),delete this._tmpForm);if(!c&&"requested"===x(v))try{var h=b.doc(b._frame),l=f.handleAs;if("html"!==
l){if("xml"===l)if("html"===h.documentElement.tagName.toLowerCase()){C("a",h.documentElement).orphan();var r=h.documentElement.innerText||h.documentElement.textContent,r=r.replace(/>\s+</g,"\x3e\x3c");a.text=A.trim(r)}else a.data=h;else a.text=h.getElementsByTagName("textarea")[0].value;H(a)}else a.data=h}catch(s){c=s}c?this.reject(c):this._finished||"requested"!==x(v)?this.resolve(a):this.reject(Error("Invalid dojo/request/iframe request state"))}function L(a){this._callNext()}function b(a,c,f){var d=
q.parseArgs(a,q.deepCreate(M,c),!0);a=d.url;c=d.options;if("GET"!==c.method&&"POST"!==c.method)throw Error(c.method+" not supported by dojo/request/iframe");b._frame||(b._frame=b.create(b._iframeName,w+"();"));a=q.deferred(d,null,I,J,K,L);a._callNext=function(){this._calledNext||(this._calledNext=!0,b._currentDfd=null,b._fireNextRequest())};a._legacy=f;b._dfdQueue.push(a);b._fireNextRequest();G(a);return f?a:a.promise}var y=E.id.replace(/[\/\.\-]/g,"_"),w=y+"_onload",v="request-download."+(new Date).getTime();
d.global[w]||(d.global[w]=function(){var a=b._currentDfd;a?a._finished=!0:b._fireNextRequest()});var M={method:"POST"};b.create=function(a,c,b){if(d.global[a])return d.global[a];if(d.global.frames[a])return d.global.frames[a];b||(t("config-useXDomain")&&t("config-dojoBlankHtmlUrl"),b=t("config-dojoBlankHtmlUrl")||F.toUrl("dojo/resources/blank.html"));c=u.place('\x3ciframe id\x3d"'+a+'" name\x3d"'+a+'" src\x3d"'+b+'" onload\x3d"'+c+'" style\x3d"position: absolute; left: 1px; top: 1px; height: 1px; width: 1px; visibility: hidden"\x3e',
d.body());return d.global[a]=c};b.doc=function(a){if(a.contentDocument)return a.contentDocument;var c=a.name;if(c){var b=d.doc.getElementsByTagName("iframe");if(a.document&&b[c].contentWindow&&b[c].contentWindow.document)return b[c].contentWindow.document;if(d.doc.frames[c]&&d.doc.frames[c].document)return d.doc.frames[c].document}return null};b.setSrc=function(a,b,f){a=d.global.frames[a.name];a.contentWindow&&(a=a.contentWindow);try{f?a.location.replace(b):a.location=b}catch(q){}};b._iframeName=
y+"_IoIframe";b._notifyStart=function(){};b._dfdQueue=[];b._currentDfd=null;b._fireNextRequest=function(){var a;try{if(!b._currentDfd&&b._dfdQueue.length){do a=b._currentDfd=b._dfdQueue.shift();while(a&&(a.canceled||a.isCanceled&&a.isCanceled())&&b._dfdQueue.length);if(!a||a.canceled||a.isCanceled&&a.isCanceled())b._currentDfd=null;else{var c=a.response,f=c.options,t=a._contentToClean=[],e=D.byId(f.form),m=q.notify,n=f.data||null,k;n["request.download-cookie"]=v;x(v,"requested");!a._legacy&&"POST"===
f.method&&!e?e=a._tmpForm=u.create("form",{name:y+"_form",style:{position:"absolute",top:"-1000px",left:"-1000px"}},d.body()):"GET"===f.method&&(e&&-1<c.url.indexOf("?"))&&(k=c.url.slice(c.url.indexOf("?")+1),n=A.mixin(B.queryToObject(k),n));if(e){if(!a._legacy){var g=e;do g=g.parentNode;while(g&&g!==d.doc.documentElement);g||(e.style.position="absolute",e.style.left="-1000px",e.style.top="-1000px",d.body().appendChild(e));e.name||(e.name=y+"_form")}if(n){var g=function(a,b){u.create("input",{type:"hidden",
name:a,value:b},e);t.push(a)},h;for(h in n){var l=n[h];if(A.isArray(l)&&1<l.length)for(k=0;k<l.length;k++)g(h,l[k]);else{var r=C("input[name\x3d'"+h+"']");-1==r.indexOf()?g(h,l):r.val(l)}}}var s=e.getAttributeNode("action"),p=e.getAttributeNode("method"),z=e.getAttributeNode("target");c.url&&(a._originalAction=s?s.value:null,s?s.value=c.url:e.setAttribute("action",c.url));if(a._legacy){if(!p||!p.value)p?p.value=f.method:e.setAttribute("method",f.method)}else a._originalMethod=p?p.value:null,p?p.value=
f.method:e.setAttribute("method",f.method);a._originalTarget=z?z.value:null;z?z.value=b._iframeName:e.setAttribute("target",b._iframeName);e.target=b._iframeName;m&&m.emit("send",c,a.promise.cancel);b._notifyStart(c);e.submit()}else f="",c.options.data&&(f=c.options.data,"string"!==typeof f&&(f=B.objectToQuery(f))),g=c.url+(-1<c.url.indexOf("?")?"\x26":"?")+f,m&&m.emit("send",c,a.promise.cancel),b._notifyStart(c),b.setSrc(b._frame,g,!0)}}}catch(w){a.reject(w)}};q.addCommonMethods(b,["GET","POST"]);
return b});
//# sourceMappingURL=iframe.js.map